name: dry-schema
codacy_id: 961f5c776f1d49218b2cede3745e059c
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Coercion and validation for data structures"
  description: |
    dry-schema provides a DSL for defining schemas with keys and rules that should be applied to
    values. It supports coercion, input sanitization, custom types and localized error messages
    (with or without I18n gem). It's also used as the schema engine in dry-validation.
  files: ["config/*.yml"]
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [dry-configurable, "~> 0.8", ">= 0.8.3"]
    - [dry-core, "~> 0.4"]
    - [dry-equalizer, "~> 0.2"]
    - [dry-initializer, "~> 3.0"]
    - [dry-logic, "~> 1.0"]
    - [dry-types, "~> 1.3", ">= 1.3.1"]
